export const FAIL_ACTION = 'ERRORS/FAIL_ACTION';
export const SUCCESS_ACTION = 'ERRORS/SUCCESS_ACTION';
export const CLOSE_ACTION = 'ERRORS/CLOSE_ACTION';
export const GET_SERVER_ERROR = 'ERRORS/GET_SERVER_ERROR';
export const CLEAR_SERVER_ERROR = 'ERRORS/CLEAR_SERVER_ERROR';
